<div data-index="4" class="bio-content bio-band page">
    <div class="bio-content__text-wrapper">
        <p class="bio-content__text">
            If there’s one thing that Dollkraut can’t stand, it’s predictability. For the past decade, bandleader Pascal Pinkert has passionately pursued musical unpredictability. As a result, the three-piece band has earned a reputation for delivering fuzzy, lo-fi and analogue-rich live performances that giddily sidestep conventions and proudly nestle in the cracks between genres.
            Pinkert initially formed the band to transform his successful solo productions into the live arena. Since making his debut in 2009, the Dutchman has brought his distinctive, anything-goes style to a stellar list of labels, including Permanent Vacation, The Gym, Tape Records Amsterdam, Charlois and, most recently, Jennifer Cardini and Noura Labbani’s Dischi Autunno.
            Delve deep into his discography – and in particular his two albums, Schimanski’s Black Lullabies (The Gym, 2014) and Holy Ghost People (Dischi Autunno, 2017) and you’ll find a dizzying range of hazy, otherworldly and mind-altering sounds. These mine the past for inspiration whilst offering a glimpse of an imagined future fraying at the seams.
            From muscular electronic disco, Morricone-inspired cinematic soundscapes and dub-flecked krautrock workouts, to electro-fired post-punk and wave, ghostly pop and freaky synthesizer explorations, Pinkert’s music surprises and thrills at every turn. Given this gleefully rough-round-the-edges eclecticism, the recent revelation that he is also the man behind Knekelhuis’s celebrated minimal wave project, De Ambassade, cannot have come as a shock.
            This unpredictability and fearlessly open-minded approach is naturally also one of the standout features of Dollkraut live performances. Performed by Pinkert alongside band-mates Rens Ottink (drums) and Timothy Francis (bass) using a range of non-conventional analogue instruments and unusual, vintage synthesizers, Dollkraut live shows combine a wall of sound and visuals with the same experimental, lo-fi approach that marks out Pinkert’s recorded output. Think members of Portishead, ESG and Joy Division jamming with Liquid Liquid and Neu!, and you’re close to the Dollkraut live sound.
            Since debuting at Holland’s revered Lowlands festival in 2015, Dollkraut has performed live to rave reviews at events including Nuits Sonores Festival in Lyon, Recontres Trans Musiciales festival in Rennes, Le Guess Who Festival, Pitch Festival and legendary Amsterdam venues Paradiso and De School. Remarkably, Dollkraut is able to make an intimate connection with their audience even at more sizeable events and spaces.
        </p>
    </div>
</div>
